language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
before_script:
  - bundle install --gemfile='gemfiles/rails2.3.gemfile'
  - bundle install --gemfile='gemfiles/rack.gemfile'
script:
  - rake appraisal:rack test
  - rake appraisal:rails2.3 test
